apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "beacon-node.fullname" . }}
  labels:
  {{- include "beacon-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 120Gi